### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Leonardo-Rocha** [rahmanfadhil/cotton#1]
## Suggestion
It would be great to have a syntax like sequelize model create that sets the fields and then add the row to the database. 

## Question
Are you planning to add more features like hooks? 

## Possible contribution
Also, I just made a method that erases the rows (with TRUNCATE) of all the tables created by models. As it's just a method I didn't bother to open a pull request and maybe there's a better approach to it like saving all created tables in the database object and obviously this command is different depending on the database. I also had to search on the folder because there may be other tables that were not created using the model, like [nessie-migrations](https://deno.land/x/nessie/) table.
```

import { walk } from 'https://deno.land/std/fs/mod.ts';
import db from '../../src/database/db.ts';

const modelsDir = './src/app/models';
const matchFilter: RegExp[] = [];
matchFilter.push(new RegExp('[:upper:]*[a-z].ts'));

/**
 * Clear all model tables from the database.
 * Uses the statement 'TRUNCATE <tablename>'
 */
export default async function truncateModels() {
  for await (const entry of walk(modelsDir, { match: matchFilter })) {
    const pathSplit = entry.path.split('/');
    const model = pathSplit[3].toLowerCase();
    const tableName = model.split('.')[0] + 's';
    await db.execute(`TRUNCATE ${tableName};`);
  }
}
```

Finally, thanks for the module! it's working great.

**Comment by rahmanfadhil** [comment]
Hi Leonardo,

Thanks for your contribution! 😁

I just added a static method called `insert` to the `Model` class, which will create the model instance and save it to the database at the same time. Check out [this commit](https://github.com/rahmanfadhil/cotton/commit/983ea1d9bfd2defa7e303bddd643c19bd6f14b86).

I also have planned to add hooks feature on the `Model` class, but I don't know exactly when it will be available.

Finally, the feature that you're proposing is very helpful, thanks! 😁

However, I think it's better to have the truncate table feature as a static method of `Model`. Truncating a table is mostly used for testing. So, I think it's better to call this method directly from the model class itself.

Example:

```ts
class Model {
  // ...

  public static async truncate(): Promise<void> {
    await this.adapter.execute(`TRUNCATE ${this.tableName}`);
  }
}
```

So, the users can simply put this in their test case.

```ts
await User.truncate()
```

What do you think? 🤔

**Comment by Leonardo-Rocha** [comment]
Insert is just what I wanted! 

And you're right, I'm using truncate for testing. The truncate (or destroy like sequelize uses) inside the model is a good approach. However, it's still important to export a list of the models added using db.AddModel, so something like this is possible:

```ts
models = db.getAllModels();
models.forEach(model => {
  await model.truncate();
});
```
Thanks!

**Comment by rahmanfadhil** [comment]
Totally agree!

Looking forward to reviewing your pull request! Let me know if you need anything from me.
