### ISSUE TITLE
Type 'URL' is not assignable to type 'string'

### ISSUE THREAD

**Issue by octavonu** [rahmanfadhil/cotton#11]
Hello,

i have tried to download your library but it is raising an error:

Am I doing something wrong?

Thank you

![image](https://user-images.githubusercontent.com/50553626/88169198-f41dd300-cc1b-11ea-99b0-1248b2a5f70d.png)

**Comment by octavonu** [comment]
My bad. The new version of deno(1.2) broke it!

**Comment by rahmanfadhil** [comment]
Hi, I actually have the same problem in Deno 1.2.

It looks like `deno-postgres` still using the older version of the standard library which doesn't support Deno 1.2 yet.

**Comment by rahmanfadhil** [comment]
It works now, Cotton now supports Deno 1.2 🎉

[Released in v0.6.4](https://github.com/rahmanfadhil/cotton/releases/tag/v0.6.4)
