### ISSUE TITLE
Novato con dudas

### ISSUE THREAD

**Issue by Juanhernandez1** [rahmanfadhil/cotton#13]
Hay forma de usar los decoradores de lo que es Model y BaseModel sin usar typescript ya que cuando uso javascript le lanza un error al ejecutar deno que dice "se esperaba token" en la línea donde se usa el decorador aun que agregó allowjs:true en tsconfig.json

**Comment by sayore** [comment]
Please use english i dont know if rahmanfadhil understands it, but in generell i would assume nearly no one can read your issue as of rn.
