### ISSUE TITLE
Maybe typo in cli.ts with migration:down command?

### ISSUE THREAD

**Issue by gbahamondezc** [rahmanfadhil/cotton#20]
Hi guys, thanks for this nice library, loved it.

I think this probably there is a typo at [cli.ts:156](https://github.com/rahmanfadhil/cotton/blob/6b3132b1c21c8ac2fa7696889657c3b0fa8f0354/cli.ts#L156) it should be `migration:down` instead of `migrations:down` ?

Running `cotton migration:down` as pointed in docs shows this error message and looks like is related to that.

![Screen Shot 2020-10-11 at 00 25 09](https://user-images.githubusercontent.com/22915623/95669532-3a6a3a80-0b58-11eb-8254-22f9b43112a4.png)

**Comment by rahmanfadhil** [comment]
Fixed, check out this [release](https://github.com/rahmanfadhil/cotton/releases/tag/v0.7.3).

Thank you very much! 😃
