### ISSUE TITLE
schema create table for null ?

### ISSUE THREAD

**Issue by TheWow** [rahmanfadhil/cotton#23]
schema columns is null  and primary
another like this
`
 await schema.createTable("test", (table) => {
    table.custom("test_id integer NOT NULL,PRIMARY KEY (test_id)");
  });
`
can i do like this 
`
    table.varchar("names", 50,isnull  or is not null);
`
thank you  for best library.

**Comment by rahmanfadhil** [comment]
You can do this:

```ts
table.varchar("names", 50).isNotNull()
```

By default, columns are allowed to be null.

Thanks for using the library! 😃
