### ISSUE TITLE
error: impossible install

### ISSUE THREAD

**Issue by ClaudioCarrera** [rahmanfadhil/cotton#29]
Hi
in version:
deno 1.4.6
v8 8.7.220.3
typescript 4.0.3

if try to install cotton cli:

Warning std versions prefixed with 'v' were deprecated recently. Please change your import to https://deno.land/std@0.63.0/fmt/colors.ts (at https://deno.land/std@v0.63.0/fmt/colors.ts)
error: Import 'https://deno.land/std@v0.63.0/fmt/colors.ts' failed: 404 Not Found
Imported from "https://deno.land/x/cotton@v0.7.2/deps.ts:12".

You can solve resolve this problem?
thanks

**Comment by rahmanfadhil** [comment]
Hi, thanks for using the library! 😃

Please update your Cotton to at least version 0.7.4.
