### ISSUE TITLE
how to delete all rows from a table

### ISSUE THREAD

**Issue by mvolkmann** [rahmanfadhil/cotton#30]
I tried this:

```js
await db.table("dogs").delete().execute();
```

but that gives the error "Cannot perform delete without any constraints!".

Is there a way to do this? I also tried this:

```js
await db.table("dogs").delete().where('name', '*').execute();
```

It seems that wildcards are not supported.

**Comment by rahmanfadhil** [comment]
Hi, thanks for using the library! 😃

The reason why I wouldn't allow anyone to delete all rows using the query builder is that it's a very dangerous thing to do (in production). It could happen if you forgot to add `WHERE` constraints to the query. However, you still can perform that action by using a raw SQL query using the `query` method like below.

```ts
await db.query("SELECT * FROM dogs")
```
