### ISSUE TITLE
Query Builder: Left Join

### ISSUE THREAD

**Issue by gabrielgrover** [rahmanfadhil/cotton#7]
Is anyone working on adding left join to query builder?  If not I would like to take a shot at it.

**Comment by sayore** [comment]
not me atm, currently only busy with the table builder in migrations 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gabrielgrover** [comment]
@rahmanfadhil ?

**Comment by rahmanfadhil** [comment]
Not me too, I'm working on a lot of missing features in Model. Feel free to send me a PR! 😁

**Comment by rahmanfadhil** [comment]
This feature is added in [v0.5.1](https://github.com/rahmanfadhil/cotton/releases/tag/v0.5.1), checkout this [commit](https://github.com/rahmanfadhil/cotton/commit/9f913de4e74dd97ace249b45693b6a83a4ed9982).
